version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      my-network:
        ipv4_address: 172.16.238.10
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app:/var/www/html
      - php_data:/usr/local/etc/php
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      my-network:
        ipv4_address: 172.16.238.20
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: mysecretpassword
    ports:
      - "8181:80"
    depends_on:
      - db
    networks:
      my-network:
        ipv4_address: 172.16.238.30

networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  db_data:
  php_data:
  app:
